name: Deploy Documentation to GitHub Pages
on:
  push:
    branches:
      - main
      - master
    tags:
      - "v*"
permissions:
  contents: write
jobs:
  deploy:
    name: Deploy Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - run: git fetch --prune --unshallow --tags

      - name: Configure Git Credentials
        run: |
          git config user.name "AgentCore CLI Bot"
          git config user.email "agentcore-cli-bot@users.noreply.github.com"

      - name: Set up Python and uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Set up Python
        run: uv python install

      - name: Install the project
        run: uv sync --all-groups --all-packages --all-extras

      - name: Validate documentation build
        run: uv run mkdocs build --strict

      # Deploy using mike for versioning support
      - name: Deploy documentation
        run: |
          uv run poe docs-deploy
